### ISSUE TITLE
Links in posts have same color as surrounding text.

### ISSUE THREAD

**Issue by witoldsz** [BrianHicks/elm-subreddit-theme#2]
Links are blended with rest of the text and it's hard to distinguish them.

See the difference:

![screenshot from 2017-02-18 03-46-08](https://cloud.githubusercontent.com/assets/544581/23089646/dff59868-f58c-11e6-89d0-5aa67f0cecc7.png)

**Comment by BrianHicks** [comment]
Thanks for the report. This pretty obviously needs to be fixed. I'll be able to do it tomorrow.

**Comment by BrianHicks** [comment]
Fixed in 507083f and deployed this morning. Thanks for your patience. :)
